application: empatio-site
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: empatio-site/static/images/favicon\.ico

- url: /static/css
  static_dir: empatio-site/static/css

- url: /static/fonts
  static_dir: empatio-site/static/fonts

- url: /static/images
  static_dir: empatio-site/static/images

- url: /static/js
  static_dir: empatio-site/static/js

- url: /static/vendors
  static_dir: empatio-site/static/vendors

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
